export const CHANGE_ELEMENT_NAME = "[CREATE ELEMENT LINKS] CHANGE NAME";
export const CHANGE_ELEMENT_DEPARTMENT =
  "[CREATE ELEMENT LINKS] CHANGE DEPARTMENT";
export const CHANGE_ELEMENT_SUBORG = "[CREATE ELEMENT LINKS] CHANGE SUBORG";
export const CHANGE_ELEMENT_JOBTITILE =
  "[CREATE ELEMENT LINKS] CHANGE JOBTITILE";
export const CHANGE_ELEMENT_LOCATION = "[CREATE ELEMENT LINKS] CHANGE LOCATION";
export const CHANGE_ELEMENT_GRADE = "[CREATE ELEMENT LINKS] CHANGE GRADE";
export const CHANGE_ELEMENT_PENSION = "[CREATE ELEMENT LINKS] CHANGE PENSION";
export const CHANGE_ELEMENT_HOUSING = "[CREATE ELEMENT LINKS] CHANGE HOUSING";
export const CHANGE_ELEMENT_LOYALTY = "[CREATE ELEMENT LINKS] CHANGE LOYALTY";
export const CHANGE_ELEMENT_AMONT = "[CREATE ELEMENT LINKS] CHANGE AMONT";
export const CHANGE_ELEMENT_STEP = "[CREATE ELEMENT LINKS] CHANGE STEP";
export const CHANGE_ELEMENT_GRADE_CATEGORY =
  "[CREATE ELEMENT LINKS] CHANGE GRADE_CATEGORY";
export const VALIDATE_ELLINKS_ERROR = "[CREATE ELEMENT LINKS] ERROR";
export const CHANGE_ELEMENT_EMPLOYEE_TYPE = "[CREATE ELEMENT LINKS]";
("[CREATE ELEMENT LINKS] CHANGE EMPLOYEE TYPE");
export const CHANGE_ELEMENT_EMPLOYEE_CATEGORY =
  "[CREATE ELEMENT LINKS] CHANGE EMPLOYEE CATEGORY";

export const GET_DEPARTMENT_SUCCESS =
  "[CREATE ELEMENT LINKS] GET DEPARTMENT SUCCESS";
export const GET_DEPARTMENT_LOADING =
  "[CREATE ELEMENT LINKS] GET DEPARTMENT LOADING";
export const GET_DEPARTMENT_ERROR =
  "[CREATE ELEMENT LINKS] GET DEPARTMENT ERROR";

export const GET_SUBORG_SUCCESS = "[CREATE ELEMENT LINKS] GET SUBORG SUCCESS";
export const GET_SUBORG_LOADING = "[CREATE ELEMENT LINKS] GET SUBORG LOADING";
export const GET_SUBORG_ERROR = "[CREATE ELEMENT LINKS] GET DEPARTMENT ERROR";

export const GET_JOBTITLE_SUCCESS =
  "[CREATE ELEMENT LINKS] GET JOBTITLE SUCCESS";
export const GET_JOBTITLE_LOADING =
  "[CREATE ELEMENT LINKS] GET JOBTITLE LOADING";
export const GET_JOBTITLE_ERROR = "[CREATE ELEMENT LINKS] GET JOBTITLE ERROR";

export const GET_LOCATION_SUCCESS =
  "[CREATE ELEMENT LINKS] GET LOCATION SUCCESS";
export const GET_LOCATION_LOADING =
  "[CREATE ELEMENT LINKS] GET LOCATION LOADING";
export const GET_LOCATION_ERROR = "[CREATE ELEMENT LINKS] GET LOCATION ERROR";

export const GET_EMPLOYEETYPE_SUCCESS =
  "[CREATE ELEMENT LINKS] GET EMPLOYEETYPE SUCCESS";
export const GET_EMPLOYEETYPE_LOADING =
  "[CREATE ELEMENT LINKS] GET EMPLOYEETYPE LOADING";
export const GET_EMPLOYEETYPE_ERROR =
  "[CREATE ELEMENT LINKS] GET EMPLOYEETYPE ERROR";

export const GET_EMPLOYEE_CATEGORY_SUCCESS =
  "[CREATE ELEMENT LINKS] GET EMPLOYEE_CATEGORY SUCCESS";
export const GET_EMPLOYEE_CATEGORY_LOADING =
  "[CREATE ELEMENT LINKS] GET EMPLOYEE_CATEGORY LOADING";
export const GET_EMPLOYEE_CATEGORY_ERROR =
  "[CREATE ELEMENT LINKS] GET EMPLOYEE_CATEGORY ERROR";

export const GET_GRADE_SUCCESS = "[CREATE ELEMENT LINKS] GET GRADE SUCCESS";
export const GET_GRADE_LOADING = "[CREATE ELEMENT LINKS] GET GRADE LOADING";
export const GET_GRADE_ERROR = "[CREATE ELEMENT LINKS] GET DEPARTMENT ERROR";

export const GET_PENSION_SUCCESS = "[CREATE ELEMENT LINKS] GET PENSION SUCCESS";
export const GET_PENSION_LOADING = "[CREATE ELEMENT LINKS] GET PENSION LOADING";
export const GET_PENSION_ERROR = "[CREATE ELEMENT LINKS] GET DEPARTMENT ERROR";

export const GET_GRADE_CATEGORY_SUCCESS =
  "[CREATE ELEMENT LINKS] GET GRADE_CATEGORY SUCCESS";
export const GET_GRADE_CATEGORY_LOADING =
  "[CREATE ELEMENT LINKS] GET GRADE_CATEGORY LOADING";
export const GET_GRADE_CATEGORY_ERROR =
  "[CREATE ELEMENT LINKS] GET GRADE_CATEGORY ERROR";

export const GET_AMOUNT_TYPE_SUCCESS =
  "[CREATE ELEMENT LINKS] GET AMOUNT_TYPE SUCCESS";
export const GET_AMOUNT_TYPE_LOADING =
  "[CREATE ELEMENT LINKS] GET AMOUNT_TYPE LOADING";
export const GET_AMOUNT_TYPE_ERROR =
  "[CREATE ELEMENT LINKS] GET AMOUNT_TYPE ERROR";
